var courses = [
	{
		"KnowlyID": "1",
		"KnowlyRemarks": "ראיון עם סבא שלי על החיים במעברה באולגה",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "חלוציות",
		"DocuType": "וידאו",
		"LoadedBy": "מיקה ישראלי",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5RY",
		"folder": "Images\\KnowliisPictures",
		"image": "book_cover.jpg",
		"Type": "ציבורי",
		"Views": "234",
		"Rank": "2",
		"Related": "תלמיד",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "2",
		"KnowlyRemarks": "כתבה ב YNET על סליקים שנמצאו בשנים האחרונות ברחבי הארץ",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "חלוציות",
		"DocuType": "לינק",
		"LoadedBy": "עמליה ארצי",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R1",
		"folder": "Images\\KnowliisPictures",
		"image": "Books-Stack-of-Red.jpg",
		"Type": "פרטי",
		"Views": "345",
		"Rank": "3",
		"Related": "מורה",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "3",
		"KnowlyRemarks": "מהאתר של מוזיאון חדרה על ההיסטוריה של חדרה",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "חלוציות",
		"DocuType": "לינק",
		"LoadedBy": "ישראל ישראלי",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R2",
		"folder": "Images\\KnowliisPictures",
		"image": "ID-10086798.jpg",
		"Type": "ציבורי",
		"Views": "456",
		"Rank": "4",
		"Related": "תלמיד",
		"Archive": "1",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "4",
		"KnowlyRemarks": "עבודת החקר שלי",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "חלוציות",
		"DocuType": "מסמך",
		"LoadedBy": "מיקה ישראלי",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R3",
		"folder": "Images\\KnowliisPictures",
		"image": "images (1).jpg",
		"Type": "פרטי",
		"Views": "123",
		"Rank": "5",
		"Related": "שלי",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "5",
		"KnowlyRemarks": "סירטון ביוטיוב על יער חדרה, האקליפטוסים מיבשים ביצות",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "חלוציות",
		"DocuType": "וידאו",
		"LoadedBy": "שלומית זיו",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R4",
		"folder": "Images\\KnowliisPictures",
		"image": "images (2).jpg",
		"Type": "ציבורי",
		"Views": "234",
		"Rank": "2",
		"Related": "מורה",
		"Archive": "1",
		"Share": "1",
		"Pin": "0"
	},
	{
		"KnowlyID": "6",
		"KnowlyRemarks": "השיפוץ של בית פיינברג וההיסטוריה של האתר",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "חלוציות",
		"DocuType": "לינק",
		"LoadedBy": "מאיה כץ",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R5",
		"folder": "Images\\KnowliisPictures",
		"image": "images (3).jpg",
		"Type": "פרטי",
		"Views": "987",
		"Rank": "3",
		"Related": "מורה",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "7",
		"KnowlyRemarks": "חדרה קולטת עלייה בשנות ה-90",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "חלוציות",
		"DocuType": "",
		"LoadedBy": "יהונתן סגל",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R6",
		"folder": "Images\\KnowliisPictures",
		"image": "images (4).jpg",
		"Type": "ציבורי",
		"Views": "654",
		"Rank": "4",
		"Related": "תלמיד",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "8",
		"KnowlyRemarks": "מעברת אגריבנק בחדרה מתוך ויקי",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "הפרויקט שלי",
		"DocuType": "לינק",
		"LoadedBy": "מיכל שפירא",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R7",
		"folder": "Images\\KnowliisPictures",
		"image": "images (5).jpg",
		"Type": "פרטי",
		"Views": "345",
		"Rank": "5",
		"Related": "של הכיתה",
		"Archive": "1",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "9",
		"KnowlyRemarks": "קטעים ממופע הסיום של בית הספר בנושא חלוציות",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "הפרויקט שלי",
		"DocuType": "",
		"LoadedBy": "איתמר בן אבי",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R8",
		"folder": "Images\\KnowliisPictures",
		"image": "images (6).jpg",
		"Type": "ציבורי",
		"Views": "789",
		"Rank": "2",
		"Related": "תלמיד",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "10",
		"KnowlyRemarks": "פרשת יציאת מצרים מוזכרת בקוראן ובמסורת האיסלאם בהרחבה. כמו כן מתוארת דמותו של משה רבנו בהערצה מהולדתו ועד למותו. הנסים אשר ארעו לישראל במצרים",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "הפרויקט שלי",
		"DocuType": "מסמך",
		"LoadedBy": "זיו חגית",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R9",
		"folder": "Images\\KnowliisPictures",
		"image": "images (7).jpg",
		"Type": "פרטי",
		"Views": "33",
		"Rank": "3",
		"Related": "מורה",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "11",
		"KnowlyRemarks": "50+ פריטים – יציאת מצרים - כל המאמרים. קוד: יציאת מצרים בתנ\"\"ך. סוג: אוסף_נושא ...",
		"OwnedByCourse": "תנ\"\"ך",
		"CourseSubject": "יציאת מצרים",
		"DocuType": "וידאו",
		"LoadedBy": "סגל לוי",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R10",
		"folder": "Images\\KnowliisPictures",
		"image": "images (8).jpg",
		"Type": "ציבורי",
		"Views": "345",
		"Rank": "4",
		"Related": "מורה",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "12",
		"KnowlyRemarks": "מילים לשיר יציאת מצרים של אתי אנקרי באתר שירונט. אתר שירונט מספק מידע על כל האמנים בישראל ובעולם, כולל מילים לשירים, אקורדים, קליפים ועוד.",
		"OwnedByCourse": "תנ\"\"ך",
		"CourseSubject": "יציאת מצרים",
		"DocuType": "מסמך",
		"LoadedBy": "ירון כץ",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R11",
		"folder": "Images\\KnowliisPictures",
		"image": "images (9).jpg",
		"Type": "פרטי",
		"Views": "5387",
		"Rank": "5",
		"Related": "שלי",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "13",
		"KnowlyRemarks": "ערב חג הפסח, \"\"כיכר השבת\"\" מגיש לצפייה הפקת ענק הממחישה את סיפוריציאת מצרים באמצעים טכנולוגיים מרהיבים. לראות, ולא להאמין. חובה לצפיה.",
		"OwnedByCourse": "תנ\"\"ך",
		"CourseSubject": "יציאת מצרים",
		"DocuType": "וידאו",
		"LoadedBy": "עמליה שפירא",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R12",
		"folder": "Images\\KnowliisPictures",
		"image": "images (10).jpg",
		"Type": "ציבורי",
		"Views": "456",
		"Rank": "2",
		"Related": "מורה",
		"Archive": "0",
		"Share": "1",
		"Pin": "0"
	},
	{
		"KnowlyID": "14",
		"KnowlyRemarks": "25 במרץ 2013 – הסיפורים בהגדת פסח נשמעים מוכרים למהגרים מאפריקה החיים בדרום ת\"\"א. בסוף השבוע 100 מהם ציינו את חג החירות האישי שלהם.",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "סתם נושא",
		"DocuType": "לינק",
		"LoadedBy": "מאיה כהן",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R13",
		"folder": "Images\\KnowliisPictures",
		"image": "images (11).jpg",
		"Type": "פרטי",
		"Views": "2687",
		"Rank": "3",
		"Related": "מורה",
		"Archive": "1",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "15",
		"KnowlyRemarks": "פר עזר ללימוד כל פרקי תכנית הלימודים המעודכנת (תשע”א) לבתי הספר הממלכתיים: פרקים מהספרים שמות, במדבר, דברים, תהלים ומשלי. הספר פותח בהתאמה לשכבת הגיל ועבר",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "סתם נושא",
		"DocuType": "מסמך",
		"LoadedBy": "דני יששכר",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R14",
		"folder": "Images\\KnowliisPictures",
		"image": "images (14).jpg",
		"Type": "ציבורי",
		"Views": "456",
		"Rank": "4",
		"Related": "תלמיד",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "16",
		"KnowlyRemarks": "סתם נושא  - בתוך הפרטי",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "סתם נושא",
		"DocuType": "לינק",
		"LoadedBy": "תלמיד 12",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R15",
		"folder": "Images\\KnowliisPictures",
		"image": "images (15).jpg",
		"Type": "פרטי",
		"Views": "32",
		"Rank": "5",
		"Related": "מורה",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "17",
		"KnowlyRemarks": "סתם נושא 2 = בתוך הפרטי",
		"OwnedByCourse": "עבודת חקר",
		"CourseSubject": "סתם נושא",
		"DocuType": "מסמך",
		"LoadedBy": "תלמיד 13",
		"Link": "http://www.youtube.com/watch?v=iTdFs4op5R16",
		"folder": "Images\\KnowliisPictures",
		"image": "images.jpg",
		"Type": "ציבורי",
		"Views": "13",
		"Rank": "3",
		"Related": "מורה",
		"Archive": "0",
		"Share": "1",
		"Pin": "0"
	},
	{
		"KnowlyID": "18",
		"KnowlyRemarks": "צילום של הדיון בנושא הפגנות",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "מסמך",
		"LoadedBy": "מיקה ישראלי",
		"Link": "",
		"folder": "Images\\KnowliisPictures",
		"image": ".jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "שלי",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "19",
		"KnowlyRemarks": "העבודה שלי. מתי מותר להפר חוקים",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "מיקה ישראלי",
		"Link": "",
		"folder": "Images\\KnowliisPictures",
		"image": ".jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "שלי",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "20",
		"KnowlyRemarks": "האתר הרישמי של צדק חברתי, אם רציתם לראות למה הם הפגינו, ומה הם עושים היום. זה המקום",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "",
		"Link": "http://j14.org.il/",
		"folder": "Images\\KnowliisPictures",
		"image": "J14.jpg",
		"Type": "ציבורי",
		"Views": "",
		"Rank": "",
		"Related": "",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "21",
		"KnowlyRemarks": "כתבה על הפגנת המליון. מדההההים",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "עמליה שפירא",
		"Link": "http://news.walla.co.il/?w=//1856617",
		"folder": "Images\\KnowliisPictures",
		"image": "1m protest.jpg",
		"Type": "",
		"Views": "",
		"Rank": "",
		"Related": "",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "22",
		"KnowlyRemarks": "איציק שמולי הוא גם תותח על וגם הבן דוד שלי. כאן הוא מדבר על החינוך. פולטיקאי פוליטקאי, אבל אחלה בנאדם",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "ירון כץ",
		"Link": "http://www.youtube.com/watch?v=lA9RCN-ZoFw",
		"folder": "Images\\KnowliisPictures",
		"image": "shmuli.jpg",
		"Type": "",
		"Views": "",
		"Rank": "",
		"Related": "",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "23",
		"KnowlyRemarks": "אמא שלי נעצרה פעם בהפגנה בשטחים על גדר ההפרדה. עשיתי איתה ראיון, והיא מספרת למה לפעמים צריך לעבור על החוק",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "מאיה כהן",
		"Link": "http://www.youtube.com/watch?v=0oTanrnDmmU",
		"folder": "Images\\KnowliisPictures",
		"image": "mymon.jpg",
		"Type": "",
		"Views": "",
		"Rank": "",
		"Related": "",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "24",
		"KnowlyRemarks": "בכתבה הבאה יש רעיונות איך אפשר לעודד הצבעה בבחירות. ביחרו רעיון והסבירו איך הייתם ממשים אותו",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "מיכל שפירא",
		"Link": "http://www.shatil.org.il/node/125215",
		"folder": "Images\\KnowliisPictures",
		"image": "shatil.jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "מורה",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "25",
		"KnowlyRemarks": "לפניכם תוצאות הבחירות האחרונות בחדרה. מצאו את התוצאות בשכונה שלכם והשוו את התוצאות . מה ניתן ללמוד?",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "מיכל שפירא",
		"Link": "http://www.votes-19.gov.il/cityresults?cityID=6500",
		"folder": "Images\\KnowliisPictures",
		"image": "results.jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "מורה",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "26",
		"KnowlyRemarks": "אחלה סיכום ללימוד למבחן. בהצלחה לכולם",
		"OwnedByCourse": "אזרחות",
		"CourseSubject": "מעורבות האזרחים במשטר",
		"DocuType": "לינק",
		"LoadedBy": "דני יששכר",
		"Link": "http://www.fxp.co.il/showthread.php?t=4926366",
		"folder": "Images\\KnowliisPictures",
		"image": "testprep.jpg",
		"Type": "",
		"Views": "",
		"Rank": "",
		"Related": "",
		"Archive": "",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "27",
		"KnowlyRemarks": "סיכום ושאלון בנושא הפחתת CO2",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "עמליה שפירא",
		"Link": "http://mybag.ebaghigh.cet.ac.il/Dashboard/Activity/ShowActivity.aspx?gItemID=fae4788f-5ff3-4386-8185-0e7127e978fa&lang=1#TabIndex=0",
		"folder": "Images\\KnowliisPictures",
		"image": "geo1.jpg",
		"Type": "פרטי",
		"Views": "87",
		"Rank": "",
		"Related": "מורה",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "28",
		"KnowlyRemarks": "הידעתם? בימי האימפריה הסוביטית, הרוסים יבשו את ימת אורל, הימה הרביעית בגודלה בעולם. הם הזיזו את כל הנהרות שהזינו אותה עד שהיא התייבשה. ובשביל מה? הרוסים רצו להיהפך למעצמת גידול כותנה, וכותנה היא גידול שצורך המון מים…",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "עמליה שפירא",
		"Link": "http://earthengine.google.org/#intro/AralSea",
		"folder": "Images\\KnowliisPictures",
		"image": "geo1.jpg",
		"Type": "פרטי",
		"Views": "1245",
		"Rank": "",
		"Related": "מורה",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "29",
		"KnowlyRemarks": "צילום של הלוח, שיעור בנושא זיהום",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "מיקה ישראלי",
		"Link": "",
		"folder": "Images\\KnowliisPictures",
		"image": "geo5.jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "שלי",
		"Archive": "",
		"Share": "0",
		"Pin": ""
	},
	{
		"KnowlyID": "30",
		"KnowlyRemarks": "צילום לוח, סיכום אקלים",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "מיקה ישראלי",
		"Link": "",
		"folder": "Images\\KnowliisPictures",
		"image": "geo6.jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "שלי",
		"Archive": "",
		"Share": "0",
		"Pin": ""
	},
	{
		"KnowlyID": "31",
		"KnowlyRemarks": "המצגת שלי בנושא השפעת האדם על צבי הים",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "ירון כץ",
		"Link": "",
		"folder": "Images\\KnowliisPictures",
		"image": "geo14.jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "שלי",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "32",
		"KnowlyRemarks": "הנה העבודה של הכיתה הנושא המדינות. ללחוץ על החיצים כדי לראות את הסיכומים",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "ירון כץ",
		"Link": "https://sites.google.com/site/pituachmedinot/",
		"folder": "Images\\KnowliisPictures",
		"image": "geo4.jpg",
		"Type": "פרטי",
		"Views": "",
		"Rank": "",
		"Related": "תלמיד",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "33",
		"KnowlyRemarks": "סיכום ושאלון בנושא הפרדת פסולת",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "דני יששכר",
		"Link": "http://sbs.cet.ac.il/Green/waste.aspx?sendingPage=GreenEnvironment/index",
		"folder": "Images\\KnowliisPictures",
		"image": "geo2.jpg",
		"Type": "ציבורי",
		"Views": "",
		"Rank": "",
		"Related": "מורה",
		"Archive": "0",
		"Share": "",
		"Pin": ""
	},
	{
		"KnowlyID": "34",
		"KnowlyRemarks": "דוח של הרשות הטבע והגנים על אישוש אוכלוסית צבי הים",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "ירון כץ",
		"Link": "",
		"folder": "Images\\KnowliisPictures",
		"image": "geo10.jpg",
		"Type": "ציבורי",
		"Views": "356",
		"Rank": "",
		"Related": "מורה",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "35",
		"KnowlyRemarks": "בים התיכון חיים שני מינים של צבי ים בלבד וגם להם נשקפת סכנת הכחדה. בדף זה מידע על ההיסטוריה של התפתחות צבי הים, על הרבייה של צבי הים, על הסכנות להם הם חשופים, על תפוצתם בים התיכון, על תכנית להגנת צבי הים בישראל של רשות שמורות הטבע ועל מנגנון ההחתמה הגנטי של צבי הים לצורך רבייה.",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "מיכל שפירא",
		"Link": "http://lib.cet.ac.il/pages/item.asp?item=3769",
		"folder": "Images\\KnowliisPictures",
		"image": "geo12.jpg",
		"Type": "ציבורי",
		"Views": "17",
		"Rank": "",
		"Related": "מורה",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "36",
		"KnowlyRemarks": "סיכום (באנגלית) על הקשר בין צבי ים ופלסטיק",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "מיכל שפירא",
		"Link": "http://www.seeturtles.org/1128/ocean-plastic.html",
		"folder": "Images\\KnowliisPictures",
		"image": "geo15.jpg",
		"Type": "ציבורי",
		"Views": "215",
		"Rank": "",
		"Related": "מורה",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "37",
		"KnowlyRemarks": "סיפור על צב ים שנשאב לטורבינות של חברת חשמל",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "מאיה כהן",
		"Link": "http://www.hnn.co.il/gallery13861.html",
		"folder": "Images\\KnowliisPictures",
		"image": "geo9.jpg",
		"Type": "ציבורי",
		"Views": "74",
		"Rank": "",
		"Related": "תלמיד",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	},
	{
		"KnowlyID": "38",
		"KnowlyRemarks": "צב שנחנק משקיות ניילון - מ ז ע ז ע ! ! !",
		"OwnedByCourse": "גאוגרפיה",
		"CourseSubject": "השפעת האדם על הסביבה",
		"DocuType": "לינק",
		"LoadedBy": "מיקה ישראלי",
		"Link": "http://ashqelon.net/?p=20313",
		"folder": "Images\\KnowliisPictures",
		"image": "geo13.jpg",
		"Type": "ציבורי",
		"Views": "36",
		"Rank": "",
		"Related": "תלמיד",
		"Archive": "0",
		"Share": "0",
		"Pin": "0"
	}
];
